# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Qfunc <- function(x, qq = 999L) {
    .Call('eBsc_Qfunc', PACKAGE = 'eBsc', x, qq)
}

eigenvalues <- function(nn, qq = 999L) {
    .Call('eBsc_eigenvalues', PACKAGE = 'eBsc', nn, qq)
}

Turn <- function(M) {
    .Call('eBsc_Turn', PACKAGE = 'eBsc', M)
}

drbasis <- function(nn, qq = 999L) {
    .Call('eBsc_drbasis', PACKAGE = 'eBsc', nn, qq)
}

rcpparma_hello_world <- function() {
    .Call('eBsc_rcpparma_hello_world', PACKAGE = 'eBsc')
}

rcpparma_outerproduct <- function(x) {
    .Call('eBsc_rcpparma_outerproduct', PACKAGE = 'eBsc', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('eBsc_rcpparma_innerproduct', PACKAGE = 'eBsc', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('eBsc_rcpparma_bothproducts', PACKAGE = 'eBsc', x)
}

